# KNP-EMI Config File
problem_type : "KNP-EMI"

# Input and output directorie
input_dir  : '/home/hherlyng/knp-emi-cgx/src/CGx/KNPEMI/input/'
output_dir : '/global/D1/homes/hherlyng/knp-emi-cgx/output/GC/5m/100c/refined/'

# Numerical parameters 
dt : 0.00005 # Timestep size 
time_steps : 100 # Number of timesteps
#T  : 50 # Simulation end time

# Problem constants (in consistent units)
physical_constants:
  T : 300   # Temperature [K]
  F : 96485 # Faraday constant [C/mol]
  R : 8.314 # Gas constant [J/(K*mol)]

C_M : 0.02 # membrane capacitance

# Mesh and meshtags files 
mesh_file      : "geometries/GC/5m/100c/mesh_refined.xdmf"
cell_tag_file  : "geometries/GC/5m/100c/mesh_refined.xdmf"
facet_tag_file : "geometries/GC/5m/100c/mesh_refined.xdmf"
mesh_conversion_factor: 1e-9

ics_tags  : !range [2, 102] # Intracellular space cell tags 
ecs_tags  : [1] # Extracellular space cell tags
boundary_tags : !range [1001, 1102] # Boundary facet tags
membrane_tags : !range [2, 102] # Membrane (interface) facet tags
glia_tags : [71, 90, 95, 100]
stimulus_tags : [56] # Membrane facet tags of the cells being stimulated

stimulus_region : 
  range : [1150, 1250]
  direction : "x"

point_evaluation :
  ics_points : [[3805, 2316, 3535]]
  ecs_points : [[1725, 3760, 3142]]
  
initial_conditions:
  phi_m_n : -0.06696676576070638
  phi_m_g : -0.07988206841052604
  Na_i_n : 10.332036868150855
  Na_i_g : 11.476992450841575
  Na_e : 104.7727183246682
  K_i_n : 120.93497281991118
  K_i_g : 145.2989368827977
  K_e : 5.350486585687688
  Cl_i_n : 9.569405793802513
  Cl_i_g : 7.269701571283548
  Cl_e : 152.99929405527774