# KNP-EMI Config File
problem_type : "KNP-EMI"

# Input and output directorie
input_dir  : '/home/hherlyng/knp-emi-cgx/src/CGx/KNPEMI/input/'
output_dir : '/global/D1/homes/hherlyng/knp-emi-cgx/output/GC/5m/10c/'

# Numerical parameters 
dt : 0.00005 # Timestep size 
time_steps : 40 # Number of timesteps
#T  : 50 # Simulation end time

# Problem constants (in consistent units)
physical_constants:
  T : 300   # Temperature [K]
  F : 96485 # Faraday constant [C/mol]
  R : 8.314 # Gas constant [J/(K*mol)]

C_M : 0.02 # membrane capacitance

# Mesh and meshtags files 
mesh_file      : "geometries/GC/5m/10c/mesh.xdmf"
cell_tag_file  : "geometries/GC/5m/10c/mesh.xdmf"
facet_tag_file : "geometries/GC/5m/10c/facets.xdmf"
mesh_conversion_factor: 1e-9

ics_tags  : !range [2, 12] # Intracellular space cell tags
ecs_tags  : [1] # Extracellular space cell tags
boundary_tags : !range [101, 112]  # Boundary facet tags
membrane_tags : !range [2, 12] # Membrane (interface) facet tags
glia_tags : [4, 10]
stimulus_tags : [5] # Membrane facet tags of the cells being stimulated

stimulus_region : 
  range : [1150, 1250]
  direction : "x"

point_evaluation :
  ics_points : [[3805, 2316, 3535]]
  ecs_points : [[1725, 3760, 3142]]