# KNP-EMI Config File
problem_type : "KNP-EMI"

# Input and output directorie
input_dir  : '/home/hherlyng/knp-emi-cgx/src/CGx/KNPEMI/geometries/GC/5m/10c/'
output_dir : '/global/D1/homes/hherlyng/knp-emi-cgx/output/GC/5m/10c/'

# Numerical parameters 
dt : 0.00005 # Timestep size 
time_steps : 500 # Number of timesteps
#T  : 50 # Simulation end time

# Problem constants (in consistent units)
physical_constants:
  T : 300   # Temperature [K]
  F : 96485 # Faraday constant [C/mol]
  R : 8.314 # Gas constant [J/(K*mol)]

C_M : 0.02 # membrane capacitance

# Mesh and meshtags files 
mesh_file      : "mesh.xdmf"
cell_tag_file  : "mesh.xdmf"
facet_tag_file : "facets.xdmf"
mesh_conversion_factor: 1e-9

ics_tags  : !range [2, 12] #[2, 3, 4, 5, 6, 7, 8, 9, 10, 11] # Intracellular space cell tags
ecs_tags  : [1] # Extracellular space cell tags
boundary_tags : !range [101, 112] #[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111] # Boundary facet tags
membrane_tags : !range [2, 12] #[2, 3, 4, 5, 6, 7, 8, 9, 10, 11] # Membrane (interface) facet tags
glia_tags : [4, 5, 7]
stimulus_tags : [3] # Membrane facet tags of the cells being stimulated

# source_terms : "ion_injection"

point_evaluation :
  ics_point : [3805, 2316, 3535]
  ecs_point : [1725, 3760, 3142]