name: CGx
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx==0.9.0
  - python
  - pandas
  - matplotlib
  - scipy
  - numpy
  - sympy
  - git
  - mpich
  - conda-ecosystem-user-package-isolation
  - pip
  - pip:
      - pyyaml
      - lxml

variables:
  PIP_NO_BUILD_ISOLATION: 0
