name: CGx
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx==0.9.0
  - python
  - pandas
  - matplotlib
  - scipy
  - numpy
  - sympy
  - git
  - mpich
  - conda-ecosystem-user-package-isolation
  - pip
  - pip:
      - "multiphenicsx@git+https://github.com/multiphenics/multiphenicsx.git@dolfinx-v0.9.0"
      - pyyaml
      - lxml
