name: CGx
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx==0.7.1
  - python=3.10
  - pandas
  - matplotlib
  - scipy
  - numpy
  - sympy
  - git
  - mpich
  - conda-ecosystem-user-package-isolation
  - pip:
      - "multiphenicsx@git+https://github.com/multiphenics/multiphenicsx.git@dolfinx-v0.7.1"
      - pyyaml


