name: CGx
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx==0.9.0
  - python=3.10
  - pandas
  - matplotlib
  - scipy
  - numpy
  - sympy
  - git
  - mpich
  - conda-ecosystem-user-package-isolation
  - pip
  - nanobind
  - scikit-build-core
  - pyyaml
  - lxml
  - cmake
  - ninja
  - cxx-compiler