## EMI Test Config File
problem_type : EMI

# I/O directories
input_dir  : './geometries/box/'
output_dir : './output/box18/'

# Numerical parameters 
dt : 0.00005 # Timestep size 
time_steps : 1000 # Number of timesteps
T   : 50 # Simulation end time

# Physical parameters
C_M : 0.02 # membrane capacitance

# Mesh and meshtags files 
mesh_file      : "box_mesh18.xdmf"
cell_tag_file  : "box_mesh18.xdmf"
facet_tag_file : "box_mesh18_facets.xdmf"

mesh_conversion_factor : 1e-6

ics_tags  : [1] # Intracellular space cell tags
ecs_tags  : [2] # Extracellular space cell tags
boundary_tags : [3] # Boundary facet tags
membrane_tags : [4] # Membrane (interface) facet tags