# Test setup with a KNP-EMI problem
problem_type : "KNP-EMI"

# Input and output directories
input_dir  : '/home/hherlyng/knp-emi-cgx/src/CGx/KNPEMI/input/'
output_dir : '/global/D1/homes/hherlyng/knp-emi-cgx/output/mms/'

# Numerical parameters 
dt : 1.0e-5 # Timestep size 
time_steps : 1 # Number of timesteps

# Problem constants (in consistent units)
physical_constants:
  T : 1.0   # Temperature [K]
  F : 1.0 # Faraday constant [C/mol]
  R : 1.0 # Gas constant [J/(K*mol)]

C_M : 1.0 # membrane capacitance

# Mesh and meshtags files 
mesh_file      : "geometries/square64.xdmf"
cell_tag_file  : "geometries/square64.xdmf"
facet_tag_file : "geometries/square64_facets.xdmf"

ics_tags  : [1] # Intracellular space cell tags
ecs_tags  : [2] # Extracellular space cell tags
boundary_tags : [8] # Boundary facet tags
membrane_tags : [1, 2, 3, 4] # Membrane (interface) facet tags
stimulus_tags : []

MMS_test:
  N_mesh : 128
  dim : 3