# KNP-EMI Config File
problem_type : "KNP-EMI"

# Input and output directorie
input_dir  : '/home/hherlyng/knp-emi-cgx/src/CGx/KNPEMI/geometries/GC/refinement_study/5m_100c/_DIR_/'
output_dir : '/global/D1/homes/hherlyng/knp-emi-cgx/output/GC/refinement_study/5m_100c/_DIR_/'

# Numerical parameters 
dt : 0.00005 # Timestep size 
time_steps : 10 # Number of timesteps

# Problem constants (in consistent units)
physical_constants:
  T : 300   # Temperature [K]
  F : 96485 # Faraday constant [C/mol]
  R : 8.314 # Gas constant [J/(K*mol)]

C_M : 0.02 # membrane capacitance

# Mesh and meshtags files 
mesh_file      : "mesh.xdmf"
cell_tag_file  : "mesh.xdmf"
facet_tag_file : "facets.xdmf"
mesh_conversion_factor: 1e-9

ics_tags  : !range [2, 102] # Intracellular space cell tags 
ecs_tags  : [1] # Extracellular space cell tags
boundary_tags : !range [1001, 1102] # Boundary facet tags
membrane_tags : !range [2, 102] # Membrane (interface) facet tags
stimulus_tags : [] # Membrane facet tags of the cells being stimulated

source_terms : "ion_injection"

point_evaluation :
  ics_point : [3805, 2316, 3535]
  ecs_point : [1725, 3760, 3142]